apiVersion: v2
name: my-headlamp-gitops
description: Helm chart để quản lý Headlamp qua GitOps
type: application
version: 1.0.0
appVersion: "1.0.0"
dependencies:
  - name: headlamp
    version: 0.25.0 # Check version mới nhất của headlamp chart nếu cần
    repository: https://kubernetes-sigs.github.io/headlamp/