headlamp:
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      kubernetes.io/ingress.class: nginx
    hosts:
      - host: k8s.dashboard.com
        paths:
          - path: /
            type: ImplementationSpecific # Một số chart cũ dùng key là 'type' thay vì 'pathType'
    tls: []