headlamp:
  ingress:
    enabled: true
    ingressClassName: nginx
    hosts:
      - host: headlamp.local
        paths:
          - path: /
            pathType: Prefix
  clusterRoleBinding:
    create: true