headlamp:
  # LƯU Ý 1: Hai dòng này cực kỳ quan trọng để Headlamp không hỏi Token nữa
  extraArgs:
    - "-in-cluster"
  automountServiceAccountToken: true
  clusterRoleBinding:
    create: true

  # LƯU Ý 2: Đoạn Ingress (giữ nguyên cấu hình cũ của bạn)
  ingress:
    enabled: true
    ingressClassName: nginx
    hosts:
      - host: k8s.dashboard.com
        paths:
          - path: /
            type: ImplementationSpecific
    tls: []